<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adam Kersivien</name>
   <tag></tag>
   <elementGuidId>49406ed9-a643-45c1-ac27-8858b026b47d</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/header/div/div/div[2]/div/div/div[2]/div/div/div/div/div[1]/div/div/i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;showMenu&quot;,[{&quot;dataSource&quot;:&quot;COECaseManager&quot;, &quot;isNavNLDeferLoaded&quot;:&quot;false&quot;, &quot;isNavTypeCustom&quot;:&quot;false&quot;, &quot;className&quot;:&quot;Data-Portal&quot;,&quot;UITemplatingStatus&quot;:&quot;Y&quot;,&quot;menuAlign&quot;:&quot;left&quot;,&quot;format&quot;:&quot;menu-format-header-menu&quot; , &quot;loadBehavior&quot;:&quot;ondisplay&quot;, &quot;ellipsisAfter&quot;:&quot;999&quot;,&quot;usingPage&quot;:&quot;pyDisplayHarness&quot;, &quot;useNewMenu&quot;:&quot;true&quot;, &quot;isMobile&quot;:&quot;false&quot;, &quot;navPageName&quot;:&quot;pyNavigation1509555129351&quot;},&quot;:event&quot;]]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andy Elliot</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Header_nav</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href_original</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20150814024324080551000</value>
   </webElementProperties>
</WebElementEntity>
