<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget2Ifr</name>
   <tag></tag>
   <elementGuidId>f54878bc-bc7c-4b60-b6bc-5de223c8a419</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PegaGadget2Ifr&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ciaqa/PRServlet/yyvmTAOnyuO4uFgx5ifNtAkEMICLuX6K*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=openWorkByHandle&amp;key=PEGASF-WORK-PROGRAM-GOLIVE%20OGL-1608&amp;contentID=bb9ba757-3fc9-de8b-f728-c47b4266adac&amp;dynamicContainerID=ecbb46ea-7810-4466-8455-a44291780118&amp;tabIndex=3&amp;prevContentID=54186251-0177-4d4b-8015-3af01cfb9555&amp;prevRecordkey=Advanced%20Search&amp;prevFormDirty=true&amp;portalThreadName=STANDARD&amp;portalName=AIAManagerPortal&amp;pzHarnessID=HID7E833DF663FC50EE80948F7911F7E03A</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
   </webElementProperties>
</WebElementEntity>
