<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>ee07466c-24ca-479e-ac39-ff83fdc91eb6</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ciaqa/PRServlet/yyvmTAOnyuO4uFgx5ifNtAkEMICLuX6K*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=display&amp;harnessName=ImplSearch&amp;className=PegaSF-Data-Portal&amp;readOnly=false&amp;label=Advanced%20Search&amp;contentID=54186251-0177-4d4b-8015-3af01cfb9555&amp;dynamicContainerID=ecbb46ea-7810-4466-8455-a44291780118&amp;tabIndex=2&amp;prevContentID=090d4da0-c83b-45a6-a8de-5adfaf948c7f&amp;prevRecordkey=PegaSF-Data-Portal%7CGoLiveHomeScreen%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=AIAManagerPortal&amp;pzHarnessID=HID7E833DF663FC50EE80948F7911F7E03A</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
</WebElementEntity>
