<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>6e803dae-9919-46af-bf73-31d6822dac71</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PegaWebGadget1&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tcpqa/PRServlet/yHepcpv0oSmliMMZ2vftcv9nXVuQs0dE*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=display&amp;harnessName=PegaCAPSearchTabUser&amp;className=Data-Portal&amp;readOnly=false&amp;label=Search&amp;contentID=6cd73d1f-7d5c-4f30-996e-1f53899fd445&amp;dynamicContainerID=ea116240-74c5-4e95-b65b-4856fb4df9a1&amp;tabIndex=2&amp;portalThreadName=STANDARD&amp;portalName=COEUserPortal7&amp;pzHarnessID=HID907FC7C519D93252296C247E512CF473</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
</WebElementEntity>
