<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>880c632b-7d6b-4bb5-a867-a24c625d54e0</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ciaqa/PRServlet/MDa-JQoW5OqxPcN40o2BRA%5B%5B*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=openWorkByHandle&amp;key=PEGASF-WORK-PROGRAM-GOLIVE%20OGL-1750&amp;contentID=dcede5ff-eb8f-0b59-4dd3-b5fc255c4be3&amp;dynamicContainerID=ecbb46ea-7810-4466-8455-a44291780118&amp;tabIndex=2&amp;prevContentID=090d4da0-c83b-45a6-a8de-5adfaf948c7f&amp;prevRecordkey=PegaSF-Data-Portal%7CGoLiveHomeScreen%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=AIAManagerPortal&amp;pzHarnessID=HID03B06DA13E1A63B145599654C119E3F2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
</WebElementEntity>
