<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ApproveStory</name>
   <tag></tag>
   <elementGuidId>6de20dbd-22ae-44ab-b2a8-421c8a00f858</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/form/div[3]/table[2]/tbody/tr/td/div/div/div[1]/div[2]/div/div/div/div/span/div/span/table/tbody/tr[1]/td/div/table[3]/tbody/tr/td/div/div/div[1]/table/tbody/tr/td[1]/table/tbody/tr/td/div/ul/li[2]/ul/li[2]/div/div/div/div/div/div/div/div/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ciaqa/PRServlet/MDa-JQoW5OqxPcN40o2BRA%5B%5B*/!TABTHREAD3?pyActivity=Assign-.ProcessAssignment&amp;InsHandle=ASSIGN-WORKBASKET PEGASF-WORK-PROGRAM-GOLIVE OGL-1722!APPROVESTORY&amp;InsClass=Assign-&amp;CurrentWorkIndex=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Announcement Details</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/GOLive_Objects/Search/Page_AIAManager/iframe_PegaGadget2Ifr</value>
   </webElementProperties>
</WebElementEntity>
