<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget2Ifr</name>
   <tag></tag>
   <elementGuidId>cd0574d5-3799-47e8-872e-f1cfa5a9cb38</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget2Ifr&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ciaqa/PRServlet/MDa-JQoW5OqxPcN40o2BRA%5B%5B*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=display&amp;harnessName=ImplSearch&amp;className=PegaSF-Data-Portal&amp;readOnly=false&amp;label=Advanced%20Search&amp;contentID=b964e578-fb31-4bf9-9523-e3b5174a003e&amp;dynamicContainerID=ecbb46ea-7810-4466-8455-a44291780118&amp;tabIndex=3&amp;prevContentID=cda8de1c-1b49-4098-8978-eb310d64e937&amp;prevRecordkey=My%20Work&amp;portalThreadName=STANDARD&amp;portalName=AIAManagerPortal&amp;pzHarnessID=HID9D758802094298985B1DBCDD953E88CF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
   </webElementProperties>
</WebElementEntity>
